name: Daily Scraper

on:
  schedule:
    - cron: '0 10 * * *'  # Run every day at 10:00 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Install Chrome
        continue-on-error: true
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libxcomposite1 libxdamage1 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run scraper
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          GITHUB_ACTIONS: 'true'
        run: |
          echo "Running scraper..."
          python src/main.py || { echo 'Scraper failed!'; exit 1; }
  
      - name: Upload scraped data
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: |
            data/
            logs/
  
      - name: Commit data back to repository
        if: success()
        run: |
          git config --global user.name 'Darshilshahcricbattle'
          git config --global user.email 'darshil@cricbattle.com'
          git add data/ logs/
          git commit -m "Daily scrape: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
